name: Build My ErgoDox EZ Firmware

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: qmkfm/qmk_firmware

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QMK environment
        run: |
          qmk setup

      - name: Build firmware
        run: |
          qmk compile -kb ergodox_ez/glow -km adv360_eq

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            ./build/ergodox_ez_glow_adv360_eq.hex

