name: Build My ErgoDox EZ Firmware

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/qmk/qmk_cli

    steps:
      - name: Disable safe.directory check
        run: git config --global --add safe.directory '*'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      # - name: Set up QMK environment
      #   run: |
      #     qmk setup

      - name: Build firmware
        run: |
          qmk compile -kb ergodox_ez/glow -km adv360_eq
      - name: List files
        run: ls -la *
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            *.bin
            *.hex

